@baseURL = http://localhost:3000

# @ref ./users.rest
@tokenAdmin = {{loginAdmin.response.body.token}}

# @ref ./users.rest
@tokenAdopter = {{loginAdopter.response.body.token}}


################################## login de users

### Fazer Login como Administrador
# @name loginAdmin
POST {{baseURL}}/login
Content-Type: application/json

{
  "email": "testeadmin@gmail.com",
  "password": "senha123"
}

### Realizar Login como Adopter (Adotante)
# @name loginAdopter
POST {{baseURL}}/login
Content-Type: application/json

{
  "email": "testeadopter@gmail.com",
  "password": "senha"
}

##################################

### Listar Todas as Adoções (Admin)
GET {{baseURL}}/adoptions
Authorization: Bearer {{tokenAdmin}}

### Realizar uma Adoção (Adopter)
POST {{baseURL}}/adoptions
Authorization: Bearer {{tokenAdopter}}
Content-Type: application/json

{
  "pet_id": 1
}