@baseURL = http://localhost:3000

# @ref ./users.rest
@tokenAdmin = {{loginAdmin.response.body.token}}

# @ref ./users.rest
@tokenAdopter = {{loginAdopter.response.body.token}}

################################## login de users

### Fazer Login como Administrador
# @name loginAdmin
POST {{baseURL}}/login
Content-Type: application/json

{
  "email": "testeadmin@gmail.com",
  "password": "senha123"
}

### Realizar Login como Adopter (Adotante)
# @name loginAdopter
POST {{baseURL}}/login
Content-Type: application/json

{
  "email": "testeadopter@gmail.com",
  "password": "senha"
}

##################################


### Listar todos os pets available
GET {{baseURL}}/pets/available

### Listar Todos os pets
GET {{baseURL}}/pets
Authorization: Bearer {{tokenAdmin}}

### Listar pet por id (admin)
GET {{baseURL}}/pets/2
Authorization: Bearer {{tokenAdopter}}

### Criar pet (admin)
POST {{baseURL}}/pets/
Authorization: Bearer {{tokenAdmin}}
Content-Type: application/json

{
  "name": "pet 3",
  "age": 2,
  "species": "cachorro",
  "size": "grande",
  "description": "descrição para teste"
}

### Criar pet (adopter)
POST {{baseURL}}/pets/
Authorization: Bearer {{tokenAdmin}}
Content-Type: application/json

{
  "name": "pet 2",
  "age": 2,
  "species": "cachorro",
  "size": "grande",
  "description": "descrição para teste"
}

### Atualizar pet (Admin)
PUT {{baseURL}}/pets/2
Authorization: Bearer {{tokenAdmin}}
Content-Type: application/json

{
  "name": "pet 2 atualizado ",
  "age": 3,
  "species": "cachorro",
  "size": "grande",
  "status": "available",
  "description": "descrição alterada com sucesso"
}

### Apagar pet (Admin)
DELETE {{baseURL}}/pets/3
Authorization: Bearer {{tokenAdmin}}