@baseURL = http://localhost:3000

### Criar usuario admin
POST {{baseURL}}/users
Content-Type: application/json

{
  "name": "teste admin ",
  "email": "testeadmin@gmail.com",
  "password": "senha123",
  "phone": "54999999999",
  "role": "admin"
}

### Criar usuario adopter
POST {{baseURL}}/users
Content-Type: application/json

{
  "name": "teste adopter",
  "email": "testeadopter@gmail.com",
  "password": "senha",
  "phone": "54999999999"
}

### Fazer Login como Administrador
# @name loginAdmin
POST {{baseURL}}/login
Content-Type: application/json

{
  "email": "testeadmin@gmail.com",
  "password": "senha123"
}

### Realizar Login como Adotante
# @name loginAdopter
POST {{baseURL}}/login
Content-Type: application/json

{
  "email": "testeadopter@gmail.com",
  "password": "senha"
}

### Listar Todos os Usuários
GET {{baseURL}}/users
Authorization: Bearer {{loginAdmin.response.body.token}}

### Listar usuario por id (admin)
GET {{baseURL}}/users/2
Authorization: Bearer {{loginAdmin.response.body.token}}

### Listar usuario por id (adopter) - listar ele mesmo
GET {{baseURL}}/users/1
Authorization: Bearer {{loginAdopter.response.body.token}}

### Admin edita qualquer usuario
PUT {{baseURL}}/users/2
Authorization: Bearer {{loginAdmin.response.body.token}}
Content-Type: application/json

{
  "name": "Alterado pelo admin",
  "email": "testeadopter@gmail.com",
  "password":"senha nova",
  "phone": "54999999999",
  "role": "adopter"
}

### Adopter deleta ele mesmo DELETE
DELETE {{baseURL}}/users/3
Authorization: Bearer {{loginAdmin.response.body.token}}